name: real_data
args: []
kwargs: {}

dataset:
  _target_: "datasets.libero_delta_dset.load_libero_slice_train_val"
  n_rollout: null
  normalize_action: ${normalize_action}
  data_path: /projects/standard/kdesingh/shared/liu03222/shared_account_dinowm_224
  split_ratio: 0.9
  val_indices:
    - 0
    - 1
  use_mmap: true
  mmap_mode: r
  image_use_mmap: true
  image_mmap_mode: r
  image_cache_size: 8
  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: ${img_size}

decoder_path: null
num_workers: 16
